apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapprc
  labels:
    team: javateamapp
  namespace: flipkart-ns
spec:
  replicas: 1
  selector:
    app: javawebapp
  template:
    metadata:
      name: javawebapprc
      labels:
        app: javawebapp
      namespace: flipkart-ns
    spec:
      containers:
      - name: javawebapp
        image: adapaladeepika/java-web-app-docker:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: flipkart-ns
spec:
  type: ClusterIP
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
